version: "3.7"

services:
  database:
    image: mariadb:5.5.56
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local